version: "3"
services:
  db:
    container_name: db
    image: postgres:alpine
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      private:

  bikeshop:
    container_name: bikeshop
    image: bikeshop:latest
    env_file: .env
    build:
      context: .
    depends_on:
      - db
    ports:
      - 3000:3000
    networks:
      public:
      private:
    volumes:
      # - .:/bikeshop
      - pub:/bikeshop/pub
      - util:/bikeshop/util
    # healthcheck:
    #   test: [ "CMD", "curl", "-f", "http://localhost/healtcheck" ]
    #   interval: 1m
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s

  proxy:
    container_name: proxy
    build:
      dockerfile: Dockerfile.nginx
    ports:
      - 80:80
    depends_on:
      - bikeshop
    networks:
      public:

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    env_file: .env
    ports:
      - 5050:80
    depends_on:
      - db
    networks:
      private:

volumes:
  pub:
  util:
  data-db:

networks:
  public:
  private:




