version: "3"
services:

  bikeshop:
    container_name: bikeshop
    env_file: .env
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    networks:
      - public
      - private
  db:
    container_name: db
    image: postgres:alpine
    env_file: .env
    ports:
      - 5432:5432
    restart: always
    volumes:
      - db-data:/var/lib/postgresql
    networks:
      - private
  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4:latest
  #   env_file: .env
  #   depends_on:
  #     - db
  #   ports:
  #     - 5050:80
  #   restart: always
networks:
  public:
  private:
volumes:
  db-data: